# Uncomment the next line to define a global platform for your project
platform :ios, '16.0'

target 'FirebaseDatabaseIssue' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Firebase', '10.25.0'
  pod 'FirebaseAuth', '10.25.0'
  pod 'FirebaseCore', '10.25.0'
  pod 'FirebaseAnalytics', '10.25.0'
  pod 'FirebaseCrashlytics', '10.25.0'
  pod 'FirebaseDatabase', '10.25.0'
  pod 'R.swift', '7.3.2'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
    end
  end
end